# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MiTrace\gui\image_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_image_dialog(object):
    def setupUi(self, image_dialog):
        image_dialog.setObjectName("image_dialog")
        image_dialog.resize(836, 583)
        self.imageLabel = QtWidgets.QLabel(image_dialog)
        self.imageLabel.setGeometry(QtCore.QRect(20, 60, 791, 501))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.label = QtWidgets.QLabel(image_dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.thresholdEditor = QtWidgets.QSpinBox(image_dialog)
        self.thresholdEditor.setGeometry(QtCore.QRect(120, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.thresholdEditor.setFont(font)
        self.thresholdEditor.setKeyboardTracking(False)
        self.thresholdEditor.setMaximum(255)
        self.thresholdEditor.setObjectName("thresholdEditor")
        self.okBt = QtWidgets.QPushButton(image_dialog)
        self.okBt.setGeometry(QtCore.QRect(270, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.okBt.setFont(font)
        self.okBt.setAutoDefault(False)
        self.okBt.setObjectName("okBt")
        self.cancelBt = QtWidgets.QPushButton(image_dialog)
        self.cancelBt.setGeometry(QtCore.QRect(390, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.cancelBt.setFont(font)
        self.cancelBt.setAutoDefault(False)
        self.cancelBt.setObjectName("cancelBt")

        self.retranslateUi(image_dialog)
        QtCore.QMetaObject.connectSlotsByName(image_dialog)

    def retranslateUi(self, image_dialog):
        _translate = QtCore.QCoreApplication.translate
        image_dialog.setWindowTitle(_translate("image_dialog", "Dialog"))
        self.label.setText(_translate("image_dialog", "Threshold:"))
        self.okBt.setText(_translate("image_dialog", "OK"))
        self.cancelBt.setText(_translate("image_dialog", "Cancel"))
